### ISSUE TITLE
Please delete this repository or change to private.

### ISSUE THREAD

**Issue by Stereoarts** [Reguluz/ReguluzToon#1]
Please check all model licenses.

**Comment by Stereoarts** [comment]
Recently foreign users can't check licenses & ignore rules  even though I recommended strongly.

**Comment by Stereoarts** [comment]
And I'll decide to discontinue their supports if you can't understand & follow the rules.

**Comment by Reguluz** [comment]
Sorry, I'll soon delete the repository and upload a new version without any illegal uploaded model.
And sorry again to add trouble to you. That's my fault
